# Generated by Django 5.0.7 on 2024-07-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_name_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='Product_images/img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('Add to Cart', 'Add to Cart'), ('Out Of Stock', 'Out Of Stock')], default='Add to Cart', max_length=200),
        ),
    ]
