# Generated by Django 5.0.7 on 2024-07-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_image_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('', '')], default='New', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('Available', 'Available'), ('Out Of Stock', 'Out Of Stock')], default='Available', max_length=200),
        ),
    ]
