# Generated by Django 5.0.7 on 2024-07-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_condition_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Sale', 'Sale')], default='New', max_length=100),
        ),
    ]
